version: "3.9"
services:
  processing:
    container_name: 'processing'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    network_mode: "host"
